from enum import StrEnum


class WebSocketErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_ACTION = "INVALID_ACTION"

    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_TOKEN = "INVALID_TOKEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"

    PRIVATE_CHAT_NOT_FOUND = "PRIVATE_CHAT_NOT_FOUND"

    USER_ALREADY_IN_GROUP = "USER_ALREADY_IN_GROUP"
    USER_NOT_IN_GROUP = "USER_NOT_IN_GROUP"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
