exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "*.ipynb",
  "prompt_defaults.py",
  "migrations",
  "**/migrations/*.py",
   "src/view",
   "tests/*.py",
   "app/UI/*.py"
  
]

# Same as Black.
line-length = 92
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
ignore = [
  "N803",
  "PLR0911",
  "S105", 
  "S106", 
  "SIM105",
  "B008",
  "PLR0917",
  "TC002",
  "PGH003",
  "FAST001",
  "PGH003",
  "E402",
  "C901",
  "W293",
  "EM101",     
  "TC001",
  "E501",
  "INP001",
  "CPY001",
  "PIE790",
  "ANN002",
  "ANN003",
  "ANN201",
  "ANN204",
  "ANN401",

  "ARG002",

  "B010",
  "B904",
  "BLE001",

  "COM812",

  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D203",
  "D205",
  "D213",
  "D401",
  "D404",
  "D417",
  "DJ001",

  "ERA001",

  "FBT001",
  "FIX002",

  "G004",

  "N818",

  "PLR0913",

  "RUF001",

  "S311",
  "SLF001",

  "TD002",
  "TD003",
  "TRY003",
  "TRY300",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[lint.per-file-ignores]
"src/view/**/*.py" = [
    "T201"
]

"**/tests/**" = [
  "C901",    # is too complex
  "D103",    # test cases could ignore docstrings
  "F401",    # unused import (test fixtures)
  "F811",    # redefined while unsed (test fixtures)
  "PLC0415", # import should be at top-level (test helpers)
  "PLR2004", # magic value (assertions)
  "PT011",   # pytest.raises too broad
  "S105",    # possible hardcoded password
  "S101",    # assert
  "TID252",  # relative imports in tests
]
"**/template.py" = [
  "E501",    # LLM prompt strings cannot be shortened
]
"**/config.py" = [
  "S105"    # ignore default values for tokens/passwords etc in config files.
]
"**/migrations/*.py" = [
  "RUF012",
  "E501",
]